#!/usr/bin/perl
use JSON::MaybeXS ();
use OracleXML;
use Policy;
use strict;
use Data::Dumper::Concise;

my $json = JSON::MaybeXS->new(utf8 => 1, pretty => 1, sort_by => 1);

foreach my $file (@ARGV) {
  my $oracle=OracleXML->new($file);
  foreach my $policy (@{$oracle->GetPolicies}) {
    print join("\t",
      $oracle->File=~s/\.\.\///r,
      $oracle->Lane,
      $oracle->Host,
      $oracle->Context, #context
      $policy->URL,
      $policy->FilterName,
      $policy->Filter,
      $policy->Filter(type=>"expr")=~s/\s+/\t/rg
      ) . "\n";
  }
}

__END__
