#!/usr/bin/perl
use OracleXML;
use Policy;
use strict;

foreach my $file (@ARGV) {
  my $oracle=OracleXML->new($file);
  foreach my $policy (@{$oracle->GetPolicies}) {
    print join("\t",
      $oracle->File=~s/\.\.\///r,
      $oracle->Lane,
      $oracle->Host,
      $oracle->Context, #context
      $policy->URL,
      $policy->FilterName,
      $policy->Filter,
      $policy->Scheme,
      $policy->Filter(type=>"expr")=~s/\s+/\t/rg
      ) . "\n";
  }
}
