#!/usr/bin/perl
use OracleXML;
use Policy;
use strict;

print "File\tLane\tHost\tContext\tURL\tFilterName\tFilter\tScheme\tAttributes\tShape\n";

foreach my $file (@ARGV) {
  my $oracle=OracleXML->new($file);
  foreach my $policy (@{$oracle->GetPolicies}) {
    print join("\t",
      $oracle->File=~s/\.\.\///r,
      $oracle->Lane,
      $oracle->Host,
      $oracle->Context,
      $policy->URL,
      $policy->FilterName,
      $policy->Filter,
      $policy->Scheme,
      join(",",sort(map {$_->{propertyName}} @{$policy->ResourceAttributes})),
      $policy->Shape=~s/\s+/\t/rg
      ) . "\n";
  }
}
